export const PRODUCTION_API = "https://api.meemong.com";
export const WEBVIEW_API_KEY =
  "$2b$10$93M3ylHjy9eC0dTahDLxR.ZGDRyRvJEiq44XiFppovFht.nBRe4p.";

export const jwt =
  "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2pvYi1hcGkubWVlbW9uZy5jb20iLCJpYXQiOjE3NTI4Nzc4MDgsInR5cGUiOiJDTElFTlRfQVBQX1VTRVIiLCJpc0RldkRhdGFiYXNlIjpmYWxzZSwiYXBwSWRlbnRpZmllcklkIjpudWxsLCJ1c2VySWQiOjQzNzkzLCJleHAiOjE3NjA2NTM4MDh9.YesyW4qZlD8yeS1kWHCL76Y5eI_kK6JtImNySQTM1OU";
